### ISSUE TITLE
Implement logging strategy more useful to tools that use the lib

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#152]
In #150, @batkinson described some of the problems with with printing to `System.out` and `System.err`. #151 gives clients of the library an opportunity to direct output to other streams. It would be even better to implement logging so that clients can pick the level of logging to see, where to the direct the logging and so on.

Some thought needs to be put into which logging library or bridge to use. I don't have a sophisticated enough understanding of the tradeoffs to decide. Briefcase uses the Apache Commons Logging [bridge](https://commons.apache.org/logging/). There would be some convenience in those matching, I think. Other options include straight `java.util.logging`, [SLF4J](https://www.slf4j.org). Maybe [LogBack](https://logback.qos.ch/) is the modern choice. @dcbriccetti, hoping you can help make an informed decision here.

**Comment by batkinson** [comment]
For whoever picks this one up, this is likely to just be a matter of picking an acceptable logging library to use across the environments javarosa is used in. I would normally use slf4j-api and leave the actual binding to the client app. We shouldn't be forcing apps to use logging library X just because someone wants to use this library. One thing to be aware of is the bytecode version used and whether it can be used with android.

**Comment by lognaturel** [comment]
Yes, agreed. I initially thought LogBack was also a bridge but it's not, it's the log4j successor. Evidently I don't know much about Java logging.

It's not clear to me what happens if the client (Briefcase) uses Apache Commons Logging and the lib (JavaRosa) uses slf4j. Do the binds happen independently and it Just Works?

**Comment by batkinson** [comment]
> It's not clear to me what happens if the client (Briefcase) uses Apache Commons Logging and the lib (JavaRosa) uses slf4j. Do the binds happen independently and it Just Works?

So, the initial motivation for slf4j was to simplify the way that the logging api is bound to the actual library. There's a fair bit of history behind this, but Jakarta Commons Logging (JCL) used (uses) a dynamic method that causes lots of trouble in certain environments, notably JavaEE web applications. Slf4j takes the dead-simple approach of requiring manual selection of the actual binding by the application developer. Specifically, only one slf4j binding can be present in the classpath. Here's one possible path using briefcase as an example:

- Convert javarosa print statements to slf4j-api logging calls
- Update briefcase to bundle the new version of javarosa with its slf4j-api transitives
- Add slf4j-jdk14 to briefcase's dependencies to bind slf4j to JUL

We could stop there, which would leave two paths to JUL. One through briefcase's commons-logging usage, and the other through javarosa's slf4j-api->slf4j-jdk14 usage. Alternatively, you can exclude JCL deps and bundle jcl-over-slf4j, which is binary compatible with commons-logging, but routes calls into slf4j instead. The benefit of that is to eliminate the dynamic binding havoc that commons-logging can inflict. However, for Swing apps, the benefit isn't as high as in managed web app environments.

Another option is to just migrate briefcase's code to slf4j-api. Often, because of the number of libraries that use JCL, you may end up having to use jcl-over-slf4j to route everything through your slf4j binding anyway. The only real immediate benefit I can think of is explicit independence from JCL in the briefcase codebase at compile-time only. Transitives may still force the runtime dependency.

**Comment by batkinson** [comment]
One thing I didn't explicitly call out that I should have...

> We could stop there, which would leave two paths to JUL... The benefit of that is to eliminate the dynamic binding havoc that commons-logging can inflict.

The other (and probably more important) benefit is that commons-logging automatically determines its binding and as does slf4j in its far simpler, but alternative method. Keeping direct JCL usage rather than replacing with jcl-over-slf4j has the disadvantage in that you're relying on two alternative methods selecting the same underlying logging system. Using jcl-over-slf4j keeps everything tidy in that it's all slf4j and its single, simple binding.

**Comment by lognaturel** [comment]
Thank you so much for that thorough explanation. `slf4j` sounds like the right way to go and it's great to know about `jcl-over-slf4j` as a first step for Briefcase and other systems that use JR.

**Comment by dcbriccetti** [comment]
Nice to have such an expert in Java logging. So it’s settled? slf4j, then? 

I suggest we do this after we get “phase 1” of external secondary instances merged.

**Comment by ggalmazor** [comment]
Just a quick update: in Briefcase, we've just adopted SLF4J with Logback bindings and JCL over SLF4J bridge for libraries that use JCL.

Also, there is an automatic JCL to SLF4J code migrator that helps you switch all your logging code to SLF4J in one sweep. We've used it on Briefcase too and it works really well.

https://www.slf4j.org/migrator.html

**Comment by ggalmazor** [comment]
I'm thinking about taking this one. Before that, I wanted to know your opinion about what level should we use to migrate current `System.out` messages. One possibility would be to use `INFO` but I haven't yet reviewed how this is used on the code (maybe it's used for debug messages, I don't know).

What do you think?

**Comment by dcbriccetti** [comment]
Keep in mind we have hooks into our writes to “out” (for @batkinson, was it?)

**Comment by ggalmazor** [comment]
> Keep in mind we have hooks into our writes to “out” 

:O Can you elaborate?

**Comment by dcbriccetti** [comment]
See `org.javarosa.core.io.Std`.

**Comment by ggalmazor** [comment]
Since all the code is going to migrate to slf4j, I'm thinking about deprecating:
- `org.javarosa.core.api.ILogger`
- `org.javarosa.core.services.Logger`

I'm in doubt with `Logger.die()`. It would have this implementation now:

```java
@Deprecated
    public static void die (String thread, Exception e) {
        //log exception
        logger.error("unhandled exception at top level", e);

        //crash
        final FatalException crashException = new FatalException("unhandled exception in " + thread, e);

        //depending on how the code was invoked, a straight 'throw' won't always reliably crash the app
        //throwing in a thread should work (at least on our nokias)
        new Thread() {
            public void run () {
                throw crashException;
            }
        }.start();

        //still do plain throw as a fallback
        try {
            Thread.sleep(3000);
        } catch (InterruptedException ie) { }
        throw crashException;
    }
```

What do you think?

**Comment by ggalmazor** [comment]
Just waiting for feedback, @opendatakit-bot. Thanks for asking
