### ISSUE TITLE
Make second parameter for round optional

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#173]
Originally filed by @martijn as opendatakit/collect#144:

> I propose to slightly adjust the round() function to make the second (decimals) argument
optional and set it to 0 if absent.
>This way we have the default XPath 1.0 behaviour but extend it if a second argument
is provided
>http://www.w3.org/TR/xpath/#function-round

**Comment by jpknox** [comment]
If I understand the problem correctly I have to write a test for, and modify, the behaviour of the `private` method called `round()` within the class `XPathFuncExpr`. I'm having trouble getting access to the `round()` method because it requires recursively going through the `eval()` method. 

Could someone point me in the right direction for how to go about accessing the `round()` method? The way it recursively uses custom objects confuses me.

**Comment by jpknox** [comment]
I overcame it with this code:
`double unround = 4;`
`Method round = xPathFuncExpr.getClass().getDeclaredMethod("round", Double.TYPE, Integer.TYPE);`
`round.setAccessible(true);`
`Double rounded = (Double) round.invoke(xPathFuncExpr, unround, 1);`
`System.out.println(rounded);`

**Comment by dcbriccetti** [comment]
It looks like this is the code to modify, in XPathFuncExpr:
```
        } else if (name.equals("round")) { // non-standard Excel-style round(value,decimal place)
            assertArgsCount(name, args, 2);
            return round(toNumeric(argVals[0]), toNumeric(argVals[1]).intValue());
```
Make It work with 1 or 2 args, and if the 2nd arg is not present, use a 0.

For the test, start looking in this section in XPathEvalTest:
```
        testEval("round('14.29123456789', 0)", 14.0);
```
Does that help?
