### ISSUE TITLE
Required message ignored when jr:requiredMsg is set

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/javarosa#275]
#### Software versions 
JavaRosa v2.8.1 and 2.8.0

#### Problem description
`jr:requiredMsg` on bind is ignored.

It was originally reported here: https://github.com/opendatakit/collect/issues/2013

#### Steps to reproduce the problem
1. Load a form with a required message such as 
[required.xml.txt](https://github.com/opendatakit/javarosa/files/1811859/required.xml.txt)
2. Swipe forward on the first question

#### Expected behavior
A custom message should be shown.

#### Other information 
The problem is caused by https://github.com/opendatakit/javarosa/pull/238
Changes implemented in that pr caused that `rows` and `requiredMsg` attributes are completely ignored and they don't exist in additionalAttributes collection like before.

So not only `requiredMsg` is broken but `rows` too (we cant specify the number of rows for StringWidgets).

**Comment by lognaturel** [comment]
Sigh. Well now we'll never forget what the whitelist is for.

**Comment by grzesiek2010** [comment]
@opendatakit-bot claim

**Comment by grzesiek2010** [comment]
I prepared a form which contains all affected attributes (`requiredMsg`, `saveincomplete`, `rows`): 
[attributes.xml.txt](https://github.com/opendatakit/javarosa/files/1812036/attributes.xml.txt)

Here is a `FormEntryPrompt` object for my `text` question:
![prompt2](https://user-images.githubusercontent.com/3276264/37416199-731a874a-27ad-11e8-8b66-17f4b5d9ace0.png)

As you can see `requiredMsg` and `saveincomplete` attributesare placed in `bindAttributes` and rows is placed in `additionalAttributes`.

Of course, it's after removing changes from #238 otherwise both collections are empty.

So fixing the regression looks easy I just need to get rid of changes from #238 but I'm wondering what is the best solution to ignore warnings mentioned in #236

I think those warnings should be added for unknown attributes that users try to add but those mentioned above are known an handled by Collect. Maybe I should just add a new collection that contains such attributes and ignores warnings for attributes that exist in that list?

@lognaturel @dcbriccetti

**Comment by lognaturel** [comment]
The change from #238 was good, it just wasn't complete. Other attributes are explicitly saved but the newly whitelisted ones aren't. Now that they're not ending up in the `additionalAttributes` collection, they're ignored. 

It would be ideal to explicitly handle the newly whitelisted attributes in the same way as the others (in other words, `requiredMsg` should be treated the same way as `constraintMsg`) but since clients already expect them to be treated as additional attributes your concept of adding a new collection seems fine, @grzesiek2010. How about `passedThroughAttributes`? The comment can say that those attributes are recognized and shouldn't result in a warning but will be passed through to the `additionalAttributes` collection. That will handle the `bind` attributes (`requiredMsg` and `saveIncomplete`). 

I'm less sure what to do with body attribute (`rows`). I suppose it too should continue being passed on for backwards compatibility. That one is so infrequently used that I think we should revert the change from #238 since it's not as straightforward as we thought and just let the warning happen.

**Comment by lognaturel** [comment]
I wasn't sure how to describe what I had in mind so I set it up at #276. It's a bigger change than your proposal @grzesiek2010 but I think it makes the intent more clear since this is an odd thing we're doing.
