### ISSUE TITLE
Add trim() / strip() custom XPath function

### ISSUE THREAD

**Issue by jkpr** [opendatakit/javarosa#460]
#### Software versions 
JavaRosa v1.x.x, Java v1.x.x, operating system: all current

#### Problem description
I would like to be able to easily strip leading and trailing whitespace in ODK. Because of how keyboards on Android tablets or phones work, spaces are often added at the end text entry. This can be a problem when trying `concat(${name}, '-', ${age})` and expecting there not to be whitespace. Another issue would be if pressing `<Enter>` and a newline is at the end of `${name}`.

The `trim` (if going with Java convention) or `strip` function just removes leading and trailing whitespace and calls `String.trim()`

#### Other information 
I have this in my fork of `javarosa` and this is the only thing preventing me from using the community version right now. It is fairly easy to add the function to `javarosa` at https://github.com/opendatakit/javarosa/blob/master/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java, and some tests at https://github.com/opendatakit/javarosa/blob/master/src/test/java/org/javarosa/xpath/test/XPathEvalTest.java, and to update the docs at https://github.com/opendatakit/docs/blob/master/odk1-src/form-operators-functions.rst#strings. I can make pull requests if those are the right places.

**Comment by lognaturel** [comment]
Thanks, @jkpr, that does seem like useful functionality! In general, we try to avoid custom functions as much as possible and instead draw from standard XPath. Would the XPath 2.0 [`normalize-space`](https://www.w3.org/TR/xpath-functions-31/#func-normalize-space) function work for your needs? It does a little bit more than what you described: it also collapses internal spaces so that "Hi   there" would become "Hi there".

**Comment by jkpr** [comment]
The function `normalize-space` does the trick, too.

**Comment by jkpr** [comment]
@lognaturel If we add `normalize-space` to the codebase, does it go in https://github.com/opendatakit/javarosa/blob/master/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java ? Also, the spec says there is zero-argument form that applies to the current context item (`.`). Would that zero-argument form be implemented? If so, is there any other function like this that I could reference?

**Comment by lognaturel** [comment]
Great, I'm glad we have a standard XPath function to match!

I hate to add more process to something that's straightforward but because JavaRosa and Collect are not the only tools that implements the [ODK XForms spec](https://opendatakit.github.io/xforms-spec/), we do have to make sure that additions like this are communicated to other members of the ecosystem.

The next step would be to write a quick forum post titled something like `ODK XForms spec proposal: add normalize-space XPath 2.0 function` for comments. Your question about adding or not the zero-arg variant would be a good question for that thread.

I'm happy to do that if you'd prefer but it'd be amazing if you're willing to do it. [Here](https://forum.opendatakit.org/t/odk-xforms-spec-proposal-add-pulldata-as-custom-xpath-function/18980) is an example of such a post. That one was more complicated and contentious. In this case, I think all you really need to say is that it's a standard XPath 2.0 function and link to the documentation. Hopefully it will get quick approval.

**Comment by lognaturel** [comment]
Thanks for https://forum.opendatakit.org/t/odk-xforms-spec-proposal-add-normalize-space-xpath-2-0-function/20990!

Woohoo, with the ok from Martijn (Enketo) and the added info that it's actually in XPath 1.0, we're a go. @jkpr if you are having trouble with the zero-argument variant, you can leave it out and we can add it later.

**Comment by lognaturel** [comment]
@jkpr would you like to also do the ODK XForms PR to be an official Spec Writer?

It would look a lot like https://github.com/opendatakit/xforms-spec/pull/107/files but with a link to the XPath 1 documentation: https://www.w3.org/TR/1999/REC-xpath-19991116/#function-normalize-space

**Comment by jkpr** [comment]
No problem. I noticed `string-length` is also supposed to allow a zero-argument form https://www.w3.org/TR/1999/REC-xpath-19991116/#function-string-length (it is right above `normalize-space`). It would have been my guide, but according to https://github.com/opendatakit/javarosa/blob/master/src/main/java/org/javarosa/xpath/expr/XPathFuncExpr.java#L391 it must have one argument. So I will stick with the one-argument version for now.
