### ISSUE TITLE
Relative references aren't correctly expanded in nested repeats

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#540]
See https://forum.opendatakit.org/t/how-to-count-repeats-in-a-inner-field/24668/3, https://forum.opendatakit.org/t/error-in-indefinite-repeat-group-inside-another-repeat-group/24729/2.

We know there was actually no support for relative references in nested repeats for some time: https://github.com/opendatakit/briefcase/issues/767#issuecomment-518839453

Possibly also related: https://github.com/opendatakit/javarosa/issues/498, https://github.com/opendatakit/javarosa/issues/135.

**Comment by ggalmazor** [comment]
Thanks for documenting this issue, @lognaturel!

It all comes down to the `TreeReference.contextualize()` method. This test describes the current behavior:

```java
TreeReference context = getRef("/data/outer[0]/inner[1]/count[0]");
assertThat(
    getRef("..").contextualize(context),
    is(getRef("/data/outer[0]/inner[1]")) // OK
);
assertThat(
    getRef("../../inner").contextualize(context),
    is(getRef("/data/outer[0]/inner[1]")) // I'd expect /data/outer[0]/inner
);
```

This unexpected behavior presents a problem with all xpath functions that work on nodesets, because we will be getting just one node when there could exist more. While studying this, I thought that a possible solution would be to change the way these functions resolve their nodesets by working with a reference that has an unbound multiplicity in its last step, regardless of what `contextualize` returns.
