### ISSUE TITLE
Allow http://openrosa.org/xforms namespace for meta

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/javarosa#60]
As shown in [ODK XForms spec examples](https://opendatakit.github.io/xforms-spec/), tags not in the W3C XForms spec should be in the `http://openrosa.org/xforms namespace`, commonly abbreviated to `orx`. In particular, `meta` and all children should really be `orx:meta`, etc.

Collect works fine with that but when I upload a form using the namespace to Aggregate, I get errors. For example, [audit-test.txt](https://github.com/opendatakit/javarosa/files/1048460/audit-test.txt) can be uploaded to Aggregate with no problems. However, when I try to upload [audit-test-orx.txt](https://github.com/opendatakit/javarosa/files/1048469/audit-test-orx.txt) I get the following error regarding `data/meta/instanceID` and `data/meta/audit`.
```
Form uploaded with warnings. There are value fields in the form that do not have <bind/> 
declarations or those <bind/> declarations do not have a type attribute that identifies the data type
of that field (e.g., boolean, int, decimal, date, dateTime, time, string, select1, select, barcode, 
geopoint or binary).
```

I haven't looked into the code at all but I suspect that there's a JavaRosa issue here. My best guess is that JavaRosa basically ignores the namespace in the instance block and then gets confused when there is one on the bind. The ideal would be for JR to accept either no namespace or `orx` for those tags. We might even consider providing a warning if the namespace isn't there.

**Comment by dcbriccetti** [comment]
Validate gives more info:

```
Parsing form...
Title: "Audit test ORX"
XForm Parse Warning: <bind> defined for a node that doesn't exist [/data/orx:meta/orx:instanceID]. The node's name was probably changed and the bind should be updated. 
XForm Parse Warning: <bind> defined for a node that doesn't exist [/data/orx:meta/orx:audit]. The node's name was probably changed and the bind should be updated. 
```

**Comment by dcbriccetti** [comment]
I simplified the input to this:
```
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms">
  <h:head>
    <h:title>Audit test ORX</h:title>
    <model>
      <instance>
        <data id="audit-test-orx">
          <orx:meta>
            <orx:audit/>
          </orx:meta>
        </data>
      </instance>
      <bind nodeset="/data/orx:meta/orx:audit" type="binary"/>
    </model>
  </h:head>
  <h:body>
  </h:body>
</h:html>
```

**Comment by dcbriccetti** [comment]
Yes, it’s a mismatch in names when trying to expand the reference.

![screen shot 2017-06-09 at 1 46 28 pm](https://user-images.githubusercontent.com/55099/26994016-9a2b6e9e-4d1a-11e7-85d6-2f90b2ada8d0.png)

**Comment by dcbriccetti** [comment]
I’ll pause for feedback. I believe the latest commits document the problem, and offer one solution. Perhaps we should make a variety of forms that we would like to parse correctly. One thing that made this hard was not assuming that the http://openrosa.org/xforms" prefix is orx. I got it working with anything.

**Comment by lognaturel** [comment]
@mdudzinski Could you please take a look at this issue and proposed approaches #68 and #74? Besides seeming strange, are there other downsides to having a namespace map where #68 puts it? Is there a perhaps even lower-impact way to allow both the standard namespace and the openrosa namespace for `meta` and its children that you can think of?

**Comment by mdudzinski** [comment]
@lognaturel sure, I'll do this.

**Comment by mdudzinski** [comment]
@lognaturel @dcbriccetti 

I agree with @dcbriccetti that passing around the map of URI and prefixes in #74 is really complex. 
I personally think that keeping the map in root `TreeElement` is not so bad because it works in the same way as kXML2 does. The `_xmldoc` field holds a reference to its children and at the first level there is an `Element` instance which points to the `<html>` node and only this instance has `prefixes` populated. 
But since each `TreeElement` has a `namespace` field then why can't we just keep the prefix as a field too?  Then we could use `TreeElementNameComparator` class but without a need to manage the map and just take the prefix from the `TreeElement treeElement`  parameter.
I actually started work on the code to confirm it works but I thought it may be a good idea to ask you for the feedback before I go too far in case I missed something. 

My initial idea was to use the `prefixes` attribute from `org.kxml2.kdom.Element` class while constructing a `TreeElement` instance but this field is null for all TreeElements besides root. Next, I hoped that using `String FEATURE_REPORT_NAMESPACE_ATTRIBUTES` in `XFormParser#getXMLDocument` method may force the parser to populate this field for each `Element` instance but this feature is not implemented in kXML2 library (http://xmlpull.org/impls.shtml).

So I think my idea now is to use `namespacePrefixesByUri` but only to populate `prefix` attribute in each `TreeElement` instance by using `namespace` instead of holding the map in the root `TreeElement` instance.

**Comment by dcbriccetti** [comment]
Hi @mdudzinski. Thanks for looking at this. I like the idea of adding a `prefix` field to `TreeElement` alongside the existing `namespace` field. I think you should try coding it.

One challenge I see (even with the code as it now stands), is that `buildInstanceStructure` is called from several places, including `XFormParser.restoreDataModel`. We don’t have the URI->prefix mapping there. I haven’t investigated how that is called.

How well do you know the ODK JavaRosa code? I’m just learning it.

**Comment by mdudzinski** [comment]
Hi @dcbriccetti.
You're right, thanks for pointing this out. I'm working on this and we'll see what can be done.

Well, I know some parts quite well because I had to deal with them when working on TaroWorks specific issues/features but only some :) I'm still learning as well. TaroWorks uses just a subset of xForm specification so now it's a bit more difficult for me to work with JavaRosa. I also need to catch-up with ODK Collect latest features etc. 

I'm also investigating how the prefixes will behave when there will be actual answers in meta data children like in #76 feature requests. I assume the prefixes should be preserved but there are no namespaces definition in an instance root node. Any ideas? Thanks!

@lognaturel

**Comment by mdudzinski** [comment]
@dcbriccetti @lognaturel 
Please check #153 where I propose my approach which is based on @dcbriccetti work.

I'm still planning to add one more test (or extend the existing one) to show that `restoreDataModel` method propagates namespaces and their prefixes properly but I need to know if you like this approach.

Let me know if I should go ahead and do the final touches.

**Comment by lognaturel** [comment]
#153 is looking good to me and it's great to see that @dcbriccetti is also on board! The next steps of testing `restoreDataModel` and removing debug logging sound perfect.

**Comment by mdudzinski** [comment]
@dcbriccetti @lognaturel 
Done. Feel free to review the updated PR.
